version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:3000" # Map host port 9002 to container port 3000
    # Load environment variables from .env.local file
    # Ensure this file exists in your project root and contains all necessary Firebase variables
    env_file:
      - .env.local
    # If you prefer to list variables explicitly or your .env.local is not picked up,
    # you can use the 'environment' block. Ensure these variables are set in your shell
    # or replace ${VARIABLE_NAME} with actual values if not using an .env file.
    # environment:
    #   - NODE_ENV=production
    #   - PORT=3000 # Next.js will use this port; it's already EXPOSEd in Dockerfile
    #   - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
    #   - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
    #   - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
    #   - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
    #   - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
    #   - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    #   - FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64}
    restart: unless-stopped
